### ISSUE TITLE
Reg Code

### ISSUE THREAD

**Issue by jaron42** [brata-hsdc/brata.masterserver#37]
We need the master server to accept the registration url with the passcode as the last element of the path and use that to look up the team as well as respond with the reg_code they should use.  There is an open issue @ellerychan is working for how the passcode and reg codes are generated so this issue will only put in the initial framework for this part of the solution and be completed with that other issue.

**Comment by ellerychan** [comment]
@jaron42:  I haven't visited that stuff in a while, but I think it should all be there.  Maybe a couple of loose ends need to be tied up, but I think the MS side of it should generate reg_codes and handle Register and Unregister messages from the Brata.  I think you will only need to make a small adjustment to the URL regex pattern (in **piservice/urls.py**) to pass the passcode in the URL, and add the passcode as an argument to the _Register.post_ method in **piservice/views.py** to make it work.

**Comment by ellerychan** [comment]
@jaron42:  I don't know if this is something you need, but there is [one commit (af03eee)](https://github.com/brata-hsdc/brata.masterserver/commit/af03eeebe391c3d54c4b4ecebaaca87fac47d941) that you might want, which is in the `leaderboard` branch, and not merged into the `hsdc2016` branch.  It is only a 2-line change, but it does change the **Team** table.  It fixes the problem we found where we couldn't add a Team through the Django admin interface because the Registration field was required.  Maybe that is not a problem for you currently.

If it is, you can just manually make the changes in your branch, or you can try to merge that commit on its own, or you can wait for the `leaderboard` branch to get merged, which @jawaad-ahmad is currently working on.

**Comment by jaron42** [comment]
Thank you for the tips.  I think I just have it about all worked out and the changes made.  I am just trying to find the algorithm for passcode generation so I can match the url change for the passcode parameter.  After that I will test it out and if it works I will commit it and make a pull request for your review to make sure I didn't mess it up too bad.
